### ISSUE TITLE
Can't use it with "TreatWarningsAsError"

### ISSUE THREAD

**Issue by carldebilly** [nventive/Uno.RoslynHelpers#4]
When activating `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` in the `csproj` file, the included content won't successfully compile.

**Comment by carldebilly** [comment]
To fix this, we need to add xml comments on every non-private members.

**Comment by Youssef1313** [comment]
I came across similar case but with `Microsoft.CodeAnalysis.NetAnalyzers`, https://github.com/unoplatform/Uno.Roslyn/pull/13.
